// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("probe_bpf")
            .map("_blob_index_", false)
            .map("_blob_ringbuf_", false)
            .map("probe_bp.rodata", false)
            .prog("bprm_committed_creds");
        builder.build()
    }
    pub struct OpenProbeMaps<'obj> {
        pub _blob_index_: libbpf_rs::OpenMapMut<'obj>,
        pub _blob_ringbuf_: libbpf_rs::OpenMapMut<'obj>,
        pub rodata: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProbeMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut _blob_index_ = None;
            let mut _blob_ringbuf_ = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "_blob_index_" => _blob_index_ = Some(map),
                    "_blob_ringbuf_" => _blob_ringbuf_ = Some(map),
                    "probe_bp.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                _blob_index_: _blob_index_.expect("map `_blob_index_` not present"),
                _blob_ringbuf_: _blob_ringbuf_.expect("map `_blob_ringbuf_` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProbeMaps<'obj> {
        pub _blob_index_: libbpf_rs::MapMut<'obj>,
        pub _blob_ringbuf_: libbpf_rs::MapMut<'obj>,
        pub rodata: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProbeMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut _blob_index_ = None;
            let mut _blob_ringbuf_ = None;
            let mut rodata = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "_blob_index_" => _blob_index_ = Some(map),
                    "_blob_ringbuf_" => _blob_ringbuf_ = Some(map),
                    "probe_bp.rodata" => rodata = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                _blob_index_: _blob_index_.expect("map `_blob_index_` not present"),
                _blob_ringbuf_: _blob_ringbuf_.expect("map `_blob_ringbuf_` not present"),
                rodata: rodata.expect("map `rodata` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenProbeProgs<'obj> {
        pub bprm_committed_creds: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProbeProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut bprm_committed_creds = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "bprm_committed_creds" => bprm_committed_creds = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                bprm_committed_creds: bprm_committed_creds
                    .expect("prog `bprm_committed_creds` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProbeProgs<'obj> {
        pub bprm_committed_creds: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProbeProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenProbeProgs<'obj>) -> Self {
            Self {
                bprm_committed_creds: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.bprm_committed_creds.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct ProbeSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> ProbeSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenProbeSkel {
                maps: unsafe { OpenProbeMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenProbeProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for ProbeSkelBuilder {
        type Output = OpenProbeSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 2],
            pub key: *mut u32,
            pub value: *mut u64,
            pub max_entries: *mut [i32; 1],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 1048576],
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct linux_binprm {
            pub file: *mut std::ffi::c_void,
            pub argc: i32,
            pub envc: i32,
            pub filename: *mut i8,
            pub interp: *mut i8,
        }
        impl Default for linux_binprm {
            fn default() -> Self {
                Self {
                    file: std::ptr::null_mut(),
                    argc: i32::default(),
                    envc: i32::default(),
                    filename: std::ptr::null_mut(),
                    interp: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub _blob_index_: __anon_1,
            pub _blob_ringbuf_: __anon_2,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct rodata {}
    }
    pub struct OpenProbeSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenProbeMaps<'obj>,
        pub progs: OpenProbeProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenProbeSkel<'obj> {
        type Output = ProbeSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<ProbeSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(ProbeSkel {
                maps: unsafe { ProbeMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: ProbeProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: ProbeLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct ProbeLinks {
        pub bprm_committed_creds: Option<libbpf_rs::Link>,
    }
    pub struct ProbeSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: ProbeMaps<'obj>,
        pub progs: ProbeProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: ProbeLinks,
    }

    unsafe impl Send for ProbeSkel<'_> {}
    unsafe impl Sync for ProbeSkel<'_> {}

    impl<'obj> Skel<'obj> for ProbeSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = ProbeLinks {
                bprm_committed_creds: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl ProbeSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 10, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97,
        98, 0, 108, 115, 109, 47, 98, 112, 114, 109, 95, 99, 111, 109, 109, 105, 116, 116, 101,
        100, 95, 99, 114, 101, 100, 115, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112,
        115, 0, 46, 114, 111, 100, 97, 116, 97, 0, 112, 114, 111, 98, 101, 46, 98, 112, 102, 46,
        99, 0, 76, 66, 66, 48, 95, 50, 49, 0, 76, 66, 66, 48, 95, 51, 0, 76, 66, 66, 48, 95, 52, 0,
        76, 66, 66, 48, 95, 53, 0, 76, 66, 66, 48, 95, 49, 54, 0, 76, 66, 66, 48, 95, 49, 56, 0,
        76, 66, 66, 48, 95, 49, 55, 0, 76, 66, 66, 48, 95, 49, 57, 0, 115, 117, 98, 109, 105, 116,
        95, 98, 108, 111, 98, 46, 95, 95, 95, 95, 102, 109, 116, 0, 76, 66, 66, 48, 95, 50, 48, 0,
        76, 66, 66, 48, 95, 57, 0, 76, 66, 66, 48, 95, 49, 48, 0, 76, 66, 66, 48, 95, 49, 53, 0,
        98, 112, 114, 109, 95, 99, 111, 109, 109, 105, 116, 116, 101, 100, 95, 99, 114, 101, 100,
        115, 0, 95, 98, 108, 111, 98, 95, 105, 110, 100, 101, 120, 95, 0, 95, 98, 108, 111, 98, 95,
        114, 105, 110, 103, 98, 117, 102, 95, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114,
        101, 108, 108, 115, 109, 47, 98, 112, 114, 109, 95, 99, 111, 109, 109, 105, 116, 116, 101,
        100, 95, 99, 114, 101, 100, 115, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 64, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 0, 0, 3, 0,
        168, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 0, 0, 3, 0, 168, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 0, 0, 0, 0, 0, 3, 0, 184, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 98, 0, 0, 0, 0, 0, 3, 0, 248, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 105, 0, 0, 0, 0, 0, 3, 0, 72, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 113, 0, 0, 0,
        0, 0, 3, 0, 136, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 121, 0, 0, 0, 0, 0, 3, 0,
        144, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 129, 0, 0, 0, 0, 0, 3, 0, 152, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 137, 0, 0, 0, 1, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22,
        0, 0, 0, 0, 0, 0, 0, 157, 0, 0, 0, 0, 0, 3, 0, 64, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 165, 0, 0, 0, 0, 0, 3, 0, 192, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 172, 0,
        0, 0, 0, 0, 3, 0, 16, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 180, 0, 0, 0, 0, 0, 3,
        0, 48, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 6, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 188, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 4,
        0, 0, 0, 0, 0, 0, 209, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0,
        0, 222, 0, 0, 0, 17, 0, 5, 0, 32, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 237, 0, 0,
        0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 121, 17, 0, 0, 0, 0, 0, 0,
        121, 17, 16, 0, 0, 0, 0, 0, 123, 26, 232, 255, 0, 0, 0, 0, 21, 1, 17, 0, 0, 0, 0, 0, 183,
        1, 0, 0, 0, 0, 0, 0, 99, 26, 248, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0,
        248, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0,
        0, 191, 7, 0, 0, 0, 0, 0, 0, 21, 7, 8, 0, 0, 0, 0, 0, 183, 8, 0, 0, 0, 0, 0, 0, 24, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 1, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 131, 0, 0, 0, 191, 6, 0, 0, 0, 0, 0, 0, 85, 6, 2, 0, 0, 0, 0, 0, 183, 0, 0,
        0, 0, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 0, 183, 1, 0, 0, 1, 0, 0, 0, 99, 22, 0, 0, 0, 0, 0,
        0, 121, 113, 0, 0, 0, 0, 0, 0, 123, 22, 8, 0, 0, 0, 0, 0, 123, 134, 16, 0, 0, 0, 0, 0, 121,
        113, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 1, 0, 0, 0, 123, 23, 0, 0, 0, 0, 0, 0, 191, 162, 0, 0,
        0, 0, 0, 0, 7, 2, 0, 0, 248, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 191, 115, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 183, 9,
        0, 0, 0, 0, 0, 0, 183, 8, 0, 0, 0, 0, 0, 0, 5, 0, 22, 0, 0, 0, 0, 0, 123, 122, 216, 255, 0,
        0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 3, 0, 0, 0, 0, 0, 0, 123,
        10, 224, 255, 0, 0, 0, 0, 133, 0, 0, 0, 131, 0, 0, 0, 191, 7, 0, 0, 0, 0, 0, 0, 121, 163,
        224, 255, 0, 0, 0, 0, 85, 7, 63, 0, 0, 0, 0, 0, 183, 7, 0, 0, 0, 0, 0, 0, 191, 99, 0, 0, 0,
        0, 0, 0, 7, 3, 0, 0, 24, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 183, 2,
        0, 0, 22, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0,
        0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 7, 9, 0, 0, 1, 0, 0, 0, 191, 118, 0, 0, 0, 0, 0, 0, 21,
        7, 214, 255, 0, 0, 0, 0, 121, 167, 232, 255, 0, 0, 0, 0, 191, 115, 0, 0, 0, 0, 0, 0, 15,
        131, 0, 0, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 24, 0, 0, 0, 183, 2, 0, 0,
        232, 0, 0, 0, 133, 0, 0, 0, 115, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 109, 1, 64, 0, 0, 0, 0,
        0, 107, 6, 2, 0, 0, 0, 0, 0, 183, 1, 0, 0, 232, 0, 0, 0, 45, 1, 13, 0, 0, 0, 0, 0, 15, 8,
        0, 0, 0, 0, 0, 0, 7, 8, 0, 0, 255, 255, 255, 255, 191, 115, 0, 0, 0, 0, 0, 0, 15, 131, 0,
        0, 0, 0, 0, 0, 191, 161, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 247, 255, 255, 255, 183, 2, 0, 0, 1,
        0, 0, 0, 133, 0, 0, 0, 113, 0, 0, 0, 113, 161, 247, 255, 0, 0, 0, 0, 21, 1, 3, 0, 0, 0, 0,
        0, 191, 145, 0, 0, 0, 0, 0, 0, 87, 1, 0, 0, 255, 255, 0, 0, 85, 1, 10, 0, 15, 0, 0, 0, 191,
        99, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 24, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 183, 2, 0, 0, 22, 0, 0, 0, 133, 0, 0, 0, 6, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 183,
        2, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 132, 0, 0, 0, 5, 0, 179, 255, 0, 0, 0, 0, 113, 103, 1,
        0, 0, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0, 99, 26, 252, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0,
        0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        133, 0, 0, 0, 1, 0, 0, 0, 21, 0, 199, 255, 0, 0, 0, 0, 183, 2, 0, 0, 0, 1, 0, 0, 21, 7,
        188, 255, 0, 0, 0, 0, 21, 7, 24, 0, 2, 0, 0, 0, 85, 7, 195, 255, 1, 0, 0, 0, 183, 2, 0, 0,
        0, 2, 0, 0, 5, 0, 184, 255, 0, 0, 0, 0, 121, 161, 216, 255, 0, 0, 0, 0, 115, 23, 1, 0, 0,
        0, 0, 0, 183, 1, 0, 0, 1, 0, 0, 0, 115, 23, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0,
        107, 39, 2, 0, 0, 0, 0, 0, 121, 49, 0, 0, 0, 0, 0, 0, 123, 23, 8, 0, 0, 0, 0, 0, 123, 39,
        16, 0, 0, 0, 0, 0, 121, 49, 0, 0, 0, 0, 0, 0, 7, 1, 0, 0, 1, 0, 0, 0, 123, 19, 0, 0, 0, 0,
        0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255, 24, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 183, 4, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 2, 0, 0, 0, 121, 113, 8, 0,
        0, 0, 0, 0, 123, 22, 16, 0, 0, 0, 0, 0, 5, 0, 173, 255, 0, 0, 0, 0, 183, 2, 0, 0, 0, 4, 0,
        0, 5, 0, 161, 255, 0, 0, 0, 0, 191, 97, 0, 0, 0, 0, 0, 0, 183, 2, 0, 0, 0, 0, 0, 0, 133, 0,
        0, 0, 133, 0, 0, 0, 5, 0, 137, 255, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 91, 68, 69, 66, 85, 71, 93, 32, 115, 116, 114, 32,
        99, 111, 112, 105, 101, 100, 32, 37, 115, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 18,
        0, 0, 0, 112, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 19, 0, 0, 0, 8, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 18, 0, 0, 0, 80, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 19, 0, 0, 0, 168, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 16, 0, 0, 0, 208, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 16, 0, 0, 0, 56, 3, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 18, 0, 0, 0, 248, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 18, 0, 0, 0,
        159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 240, 2, 0, 0, 240, 2, 0, 0, 192, 5, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0,
        0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 8, 7, 0, 0, 0,
        34, 0, 0, 0, 0, 0, 0, 8, 8, 0, 0, 0, 45, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 10, 0, 0, 0, 58, 0, 0, 0, 0, 0, 0, 8, 11, 0, 0, 0, 67, 0, 0, 0, 0, 0,
        0, 8, 12, 0, 0, 0, 78, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 97, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 102, 0, 0, 0, 5, 0,
        0, 0, 64, 0, 0, 0, 106, 0, 0, 0, 9, 0, 0, 0, 128, 0, 0, 0, 112, 0, 0, 0, 13, 0, 0, 0, 192,
        0, 0, 0, 124, 0, 0, 0, 0, 0, 0, 14, 15, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 18, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0,
        16, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0, 97, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 112, 0,
        0, 0, 19, 0, 0, 0, 64, 0, 0, 0, 137, 0, 0, 0, 0, 0, 0, 14, 21, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 152, 0, 0, 0, 23, 0, 0,
        0, 156, 0, 0, 0, 1, 0, 0, 12, 24, 0, 0, 0, 177, 0, 0, 0, 5, 0, 0, 4, 32, 0, 0, 0, 190, 0,
        0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 195, 0, 0, 0, 2, 0, 0, 0, 64, 0, 0, 0, 200, 0, 0, 0, 2, 0,
        0, 0, 96, 0, 0, 0, 205, 0, 0, 0, 28, 0, 0, 0, 128, 0, 0, 0, 214, 0, 0, 0, 28, 0, 0, 0, 192,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 29, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 10, 30, 0, 0, 0, 221, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 3, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 226, 0, 0, 0, 0, 0, 0, 14, 31,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 29, 0, 0, 0, 4, 0, 0, 0, 22, 0, 0,
        0, 235, 0, 0, 0, 0, 0, 0, 14, 33, 0, 0, 0, 0, 0, 0, 0, 190, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0,
        0, 145, 5, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 153, 5, 0,
        0, 2, 0, 0, 15, 48, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 22, 0, 0, 0, 32, 0, 0,
        0, 16, 0, 0, 0, 159, 5, 0, 0, 1, 0, 0, 15, 22, 0, 0, 0, 34, 0, 0, 0, 0, 0, 0, 0, 22, 0, 0,
        0, 0, 105, 110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69,
        95, 95, 0, 117, 105, 110, 116, 51, 50, 95, 116, 0, 95, 95, 117, 105, 110, 116, 51, 50, 95,
        116, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 117, 105, 110, 116,
        54, 52, 95, 116, 0, 95, 95, 117, 105, 110, 116, 54, 52, 95, 116, 0, 117, 110, 115, 105,
        103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 116, 121, 112, 101,
        0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105,
        101, 115, 0, 95, 98, 108, 111, 98, 95, 105, 110, 100, 101, 120, 95, 0, 95, 98, 108, 111,
        98, 95, 114, 105, 110, 103, 98, 117, 102, 95, 0, 99, 116, 120, 0, 98, 112, 114, 109, 95,
        99, 111, 109, 109, 105, 116, 116, 101, 100, 95, 99, 114, 101, 100, 115, 0, 108, 105, 110,
        117, 120, 95, 98, 105, 110, 112, 114, 109, 0, 102, 105, 108, 101, 0, 97, 114, 103, 99, 0,
        101, 110, 118, 99, 0, 102, 105, 108, 101, 110, 97, 109, 101, 0, 105, 110, 116, 101, 114,
        112, 0, 99, 104, 97, 114, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 115, 117, 98, 109,
        105, 116, 95, 98, 108, 111, 98, 46, 95, 95, 95, 95, 102, 109, 116, 0, 47, 114, 111, 111,
        116, 47, 98, 112, 102, 47, 114, 117, 115, 116, 47, 108, 105, 98, 47, 46, 46, 47, 46, 46,
        47, 99, 47, 115, 114, 99, 47, 98, 112, 114, 109, 95, 99, 111, 109, 109, 105, 116, 116, 101,
        100, 95, 99, 114, 101, 100, 115, 47, 112, 114, 111, 98, 101, 46, 98, 112, 102, 46, 99, 0,
        105, 110, 116, 32, 66, 80, 70, 95, 80, 82, 79, 71, 40, 98, 112, 114, 109, 95, 99, 111, 109,
        109, 105, 116, 116, 101, 100, 95, 99, 114, 101, 100, 115, 44, 32, 99, 111, 110, 115, 116,
        32, 115, 116, 114, 117, 99, 116, 32, 108, 105, 110, 117, 120, 95, 98, 105, 110, 112, 114,
        109, 32, 42, 98, 112, 114, 109, 41, 32, 123, 0, 32, 32, 99, 111, 112, 121, 95, 115, 116,
        114, 95, 116, 111, 95, 98, 108, 111, 98, 40, 98, 112, 114, 109, 45, 62, 102, 105, 108, 101,
        110, 97, 109, 101, 44, 32, 38, 98, 108, 111, 98, 95, 105, 100, 44, 32, 38, 115, 116, 114,
        95, 108, 101, 110, 44, 32, 83, 73, 90, 69, 95, 50, 53, 54, 41, 59, 0, 47, 114, 111, 111,
        116, 47, 98, 112, 102, 47, 114, 117, 115, 116, 47, 108, 105, 98, 47, 46, 46, 47, 46, 46,
        47, 99, 47, 115, 114, 99, 47, 99, 111, 109, 109, 111, 110, 47, 98, 108, 111, 98, 46, 104,
        0, 32, 32, 105, 102, 32, 40, 33, 115, 116, 114, 32, 124, 124, 32, 33, 98, 108, 111, 98, 95,
        105, 100, 32, 124, 124, 32, 33, 115, 116, 114, 95, 108, 101, 110, 41, 32, 123, 0, 32, 32,
        117, 105, 110, 116, 51, 50, 95, 116, 32, 122, 101, 114, 111, 32, 61, 32, 48, 59, 0, 32, 32,
        117, 105, 110, 116, 54, 52, 95, 116, 42, 32, 98, 108, 111, 98, 95, 105, 100, 32, 61, 32,
        98, 112, 102, 95, 109, 97, 112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108, 101, 109,
        40, 38, 95, 98, 108, 111, 98, 95, 105, 110, 100, 101, 120, 95, 44, 32, 38, 122, 101, 114,
        111, 41, 59, 0, 32, 32, 105, 102, 32, 40, 33, 98, 108, 111, 98, 95, 105, 100, 41, 32, 123,
        0, 32, 32, 105, 102, 32, 40, 33, 98, 108, 111, 98, 41, 32, 123, 0, 32, 32, 98, 108, 111,
        98, 45, 62, 32, 118, 101, 114, 115, 105, 111, 110, 32, 61, 32, 48, 120, 48, 49, 59, 0, 32,
        32, 98, 108, 111, 98, 45, 62, 98, 108, 111, 98, 95, 105, 100, 32, 61, 32, 42, 98, 108, 111,
        98, 95, 105, 100, 59, 0, 32, 32, 98, 108, 111, 98, 45, 62, 98, 108, 111, 98, 95, 110, 101,
        120, 116, 32, 61, 32, 48, 59, 0, 32, 32, 42, 98, 108, 111, 98, 95, 105, 100, 32, 61, 32,
        42, 98, 108, 111, 98, 95, 105, 100, 32, 43, 32, 49, 59, 0, 32, 32, 98, 112, 102, 95, 109,
        97, 112, 95, 117, 112, 100, 97, 116, 101, 95, 101, 108, 101, 109, 40, 38, 95, 98, 108, 111,
        98, 95, 105, 110, 100, 101, 120, 95, 44, 32, 38, 122, 101, 114, 111, 44, 32, 98, 108, 111,
        98, 95, 105, 100, 44, 32, 66, 80, 70, 95, 65, 78, 89, 41, 59, 0, 32, 32, 98, 112, 102, 95,
        112, 114, 105, 110, 116, 107, 40, 34, 91, 68, 69, 66, 85, 71, 93, 32, 115, 116, 114, 32,
        99, 111, 112, 105, 101, 100, 32, 37, 115, 34, 44, 32, 40, 40, 108, 119, 95, 98, 108, 111,
        98, 42, 41, 98, 108, 111, 98, 41, 45, 62, 100, 97, 116, 97, 41, 59, 0, 32, 32, 98, 112,
        102, 95, 114, 105, 110, 103, 98, 117, 102, 95, 115, 117, 98, 109, 105, 116, 40, 98, 108,
        111, 98, 44, 32, 48, 41, 59, 0, 32, 32, 102, 111, 114, 32, 40, 117, 105, 110, 116, 49, 54,
        95, 116, 32, 105, 32, 61, 32, 48, 59, 32, 105, 32, 60, 32, 77, 65, 88, 95, 66, 76, 79, 66,
        83, 32, 38, 38, 32, 98, 108, 111, 98, 59, 32, 105, 43, 43, 41, 32, 123, 0, 32, 32, 32, 32,
        108, 111, 110, 103, 32, 108, 101, 110, 32, 61, 32, 98, 112, 102, 95, 112, 114, 111, 98,
        101, 95, 114, 101, 97, 100, 95, 107, 101, 114, 110, 101, 108, 95, 115, 116, 114, 40, 98,
        108, 111, 98, 45, 62, 100, 97, 116, 97, 44, 32, 115, 105, 122, 101, 44, 32, 115, 116, 114,
        32, 43, 32, 116, 111, 116, 97, 108, 95, 99, 111, 112, 105, 101, 100, 41, 59, 0, 32, 32, 32,
        32, 105, 102, 32, 40, 108, 101, 110, 32, 60, 32, 48, 41, 32, 123, 0, 32, 32, 32, 32, 98,
        108, 111, 98, 45, 62, 100, 97, 116, 97, 95, 115, 105, 122, 101, 32, 61, 32, 108, 101, 110,
        59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 108, 101, 110, 32, 60, 32, 115, 105, 122, 101, 41,
        32, 123, 0, 32, 32, 32, 32, 98, 112, 102, 95, 112, 114, 111, 98, 101, 95, 114, 101, 97,
        100, 95, 107, 101, 114, 110, 101, 108, 40, 38, 108, 97, 115, 116, 44, 32, 49, 44, 32, 115,
        116, 114, 32, 43, 32, 116, 111, 116, 97, 108, 95, 99, 111, 112, 105, 101, 100, 41, 59, 0,
        32, 32, 32, 32, 105, 102, 32, 40, 108, 97, 115, 116, 32, 61, 61, 32, 48, 41, 32, 123, 0,
        32, 32, 32, 32, 105, 102, 32, 40, 105, 32, 61, 61, 32, 77, 65, 88, 95, 66, 76, 79, 66, 83,
        32, 45, 32, 49, 41, 32, 123, 0, 32, 32, 108, 119, 95, 98, 108, 111, 98, 32, 42, 110, 101,
        120, 116, 32, 61, 32, 114, 101, 115, 101, 114, 118, 101, 95, 98, 108, 111, 98, 40, 98, 108,
        111, 98, 45, 62, 98, 108, 111, 98, 95, 115, 105, 122, 101, 41, 59, 0, 32, 32, 115, 119,
        105, 116, 99, 104, 32, 40, 98, 108, 111, 98, 95, 115, 105, 122, 101, 41, 32, 123, 0, 32,
        32, 98, 108, 111, 98, 45, 62, 98, 108, 111, 98, 95, 115, 105, 122, 101, 32, 61, 32, 98,
        108, 111, 98, 95, 115, 105, 122, 101, 59, 0, 32, 32, 98, 108, 111, 98, 45, 62, 100, 97,
        116, 97, 95, 115, 105, 122, 101, 32, 61, 32, 48, 59, 0, 32, 32, 32, 32, 98, 108, 111, 98,
        45, 62, 98, 108, 111, 98, 95, 110, 101, 120, 116, 32, 61, 32, 110, 101, 120, 116, 45, 62,
        98, 108, 111, 98, 95, 105, 100, 59, 0, 32, 32, 98, 112, 102, 95, 114, 105, 110, 103, 98,
        117, 102, 95, 100, 105, 115, 99, 97, 114, 100, 40, 98, 108, 111, 98, 44, 32, 48, 41, 59, 0,
        48, 58, 51, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 109, 97, 112, 115, 0, 46, 114, 111,
        100, 97, 116, 97, 0, 108, 115, 109, 47, 98, 112, 114, 109, 95, 99, 111, 109, 109, 105, 116,
        116, 101, 100, 95, 99, 114, 101, 100, 115, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20,
        0, 0, 0, 20, 0, 0, 0, 204, 3, 0, 0, 224, 3, 0, 0, 28, 0, 0, 0, 8, 0, 0, 0, 167, 5, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 16, 0, 0, 0, 167, 5, 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 255,
        0, 0, 0, 63, 1, 0, 0, 5, 76, 0, 0, 8, 0, 0, 0, 255, 0, 0, 0, 133, 1, 0, 0, 26, 88, 0, 0,
        24, 0, 0, 0, 199, 1, 0, 0, 244, 1, 0, 0, 12, 220, 1, 0, 40, 0, 0, 0, 199, 1, 0, 0, 26, 2,
        0, 0, 12, 156, 0, 0, 56, 0, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 199,
        1, 0, 0, 47, 2, 0, 0, 23, 160, 0, 0, 96, 0, 0, 0, 199, 1, 0, 0, 112, 2, 0, 0, 7, 164, 0, 0,
        112, 0, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 199, 1, 0, 0, 130, 2, 0,
        0, 7, 252, 0, 0, 168, 0, 0, 0, 255, 0, 0, 0, 63, 1, 0, 0, 5, 76, 0, 0, 192, 0, 0, 0, 199,
        1, 0, 0, 145, 2, 0, 0, 18, 12, 1, 0, 200, 0, 0, 0, 199, 1, 0, 0, 170, 2, 0, 0, 19, 24, 1,
        0, 208, 0, 0, 0, 199, 1, 0, 0, 170, 2, 0, 0, 17, 24, 1, 0, 216, 0, 0, 0, 199, 1, 0, 0, 198,
        2, 0, 0, 19, 28, 1, 0, 224, 0, 0, 0, 199, 1, 0, 0, 221, 2, 0, 0, 14, 36, 1, 0, 232, 0, 0,
        0, 199, 1, 0, 0, 221, 2, 0, 0, 23, 36, 1, 0, 240, 0, 0, 0, 199, 1, 0, 0, 221, 2, 0, 0, 12,
        36, 1, 0, 0, 1, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 1, 0, 0, 199, 1, 0, 0, 248,
        2, 0, 0, 3, 40, 1, 0, 72, 1, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 136, 1, 0, 0, 199,
        1, 0, 0, 130, 2, 0, 0, 7, 252, 0, 0, 152, 1, 0, 0, 199, 1, 0, 0, 55, 3, 0, 0, 3, 64, 1, 0,
        200, 1, 0, 0, 199, 1, 0, 0, 118, 3, 0, 0, 3, 68, 1, 0, 224, 1, 0, 0, 199, 1, 0, 0, 149, 3,
        0, 0, 48, 248, 1, 0, 240, 1, 0, 0, 199, 1, 0, 0, 149, 3, 0, 0, 3, 248, 1, 0, 0, 2, 0, 0,
        199, 1, 0, 0, 202, 3, 0, 0, 64, 96, 2, 0, 16, 2, 0, 0, 199, 1, 0, 0, 202, 3, 0, 0, 42, 96,
        2, 0, 32, 2, 0, 0, 199, 1, 0, 0, 202, 3, 0, 0, 16, 96, 2, 0, 48, 2, 0, 0, 199, 1, 0, 0, 26,
        4, 0, 0, 9, 100, 2, 0, 64, 2, 0, 0, 199, 1, 0, 0, 45, 4, 0, 0, 21, 120, 2, 0, 72, 2, 0, 0,
        199, 1, 0, 0, 72, 4, 0, 0, 9, 128, 2, 0, 88, 2, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        104, 2, 0, 0, 199, 1, 0, 0, 94, 4, 0, 0, 41, 152, 2, 0, 128, 2, 0, 0, 199, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 136, 2, 0, 0, 199, 1, 0, 0, 94, 4, 0, 0, 5, 152, 2, 0, 152, 2, 0, 0, 199,
        1, 0, 0, 151, 4, 0, 0, 9, 160, 2, 0, 160, 2, 0, 0, 199, 1, 0, 0, 151, 4, 0, 0, 9, 160, 2,
        0, 168, 2, 0, 0, 199, 1, 0, 0, 172, 4, 0, 0, 11, 184, 2, 0, 184, 2, 0, 0, 199, 1, 0, 0,
        172, 4, 0, 0, 9, 184, 2, 0, 192, 2, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 3, 0,
        0, 199, 1, 0, 0, 202, 4, 0, 0, 38, 124, 1, 0, 24, 3, 0, 0, 199, 1, 0, 0, 26, 2, 0, 0, 12,
        156, 0, 0, 48, 3, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 56, 3, 0, 0, 199, 1, 0, 0,
        47, 2, 0, 0, 23, 160, 0, 0, 80, 3, 0, 0, 199, 1, 0, 0, 112, 2, 0, 0, 7, 164, 0, 0, 96, 3,
        0, 0, 199, 1, 0, 0, 251, 4, 0, 0, 3, 188, 0, 0, 136, 3, 0, 0, 199, 1, 0, 0, 18, 5, 0, 0,
        19, 16, 1, 0, 152, 3, 0, 0, 199, 1, 0, 0, 145, 2, 0, 0, 18, 12, 1, 0, 176, 3, 0, 0, 199, 1,
        0, 0, 49, 5, 0, 0, 19, 20, 1, 0, 184, 3, 0, 0, 199, 1, 0, 0, 170, 2, 0, 0, 19, 24, 1, 0,
        192, 3, 0, 0, 199, 1, 0, 0, 170, 2, 0, 0, 17, 24, 1, 0, 200, 3, 0, 0, 199, 1, 0, 0, 198, 2,
        0, 0, 19, 28, 1, 0, 208, 3, 0, 0, 199, 1, 0, 0, 221, 2, 0, 0, 14, 36, 1, 0, 216, 3, 0, 0,
        199, 1, 0, 0, 221, 2, 0, 0, 23, 36, 1, 0, 224, 3, 0, 0, 199, 1, 0, 0, 221, 2, 0, 0, 12, 36,
        1, 0, 240, 3, 0, 0, 199, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 3, 0, 0, 199, 1, 0, 0, 248,
        2, 0, 0, 3, 40, 1, 0, 24, 4, 0, 0, 199, 1, 0, 0, 72, 5, 0, 0, 29, 132, 1, 0, 32, 4, 0, 0,
        199, 1, 0, 0, 72, 5, 0, 0, 21, 132, 1, 0, 64, 4, 0, 0, 199, 1, 0, 0, 109, 5, 0, 0, 3, 84,
        1, 0, 16, 0, 0, 0, 167, 5, 0, 0, 1, 0, 0, 0, 8, 0, 0, 0, 26, 0, 0, 0, 141, 5, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 33, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 3, 0, 0, 0, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 7, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0,
        0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 7, 0, 0, 0, 0, 0, 0,
        48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 56, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 7, 0,
        0, 0, 0, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 246, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 16, 8, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 19, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 144, 8, 0, 0, 0, 0, 0, 0, 200, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 88, 17, 0, 0, 0, 0, 0, 0, 28, 4, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
