// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("probe_bpf")
            .map("blob_ringbuf", false)
            .map("signal_ringbuf", false)
            .map("_blob_index_", false)
            .map("_lw_task_storage_", false);
        builder.build()
    }
    pub struct OpenProbeMaps<'obj> {
        pub blob_ringbuf: libbpf_rs::OpenMapMut<'obj>,
        pub signal_ringbuf: libbpf_rs::OpenMapMut<'obj>,
        pub _blob_index_: libbpf_rs::OpenMapMut<'obj>,
        pub _lw_task_storage_: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProbeMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut blob_ringbuf = None;
            let mut signal_ringbuf = None;
            let mut _blob_index_ = None;
            let mut _lw_task_storage_ = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "blob_ringbuf" => blob_ringbuf = Some(map),
                    "signal_ringbuf" => signal_ringbuf = Some(map),
                    "_blob_index_" => _blob_index_ = Some(map),
                    "_lw_task_storage_" => _lw_task_storage_ = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                blob_ringbuf: blob_ringbuf.expect("map `blob_ringbuf` not present"),
                signal_ringbuf: signal_ringbuf.expect("map `signal_ringbuf` not present"),
                _blob_index_: _blob_index_.expect("map `_blob_index_` not present"),
                _lw_task_storage_: _lw_task_storage_.expect("map `_lw_task_storage_` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProbeMaps<'obj> {
        pub blob_ringbuf: libbpf_rs::MapMut<'obj>,
        pub signal_ringbuf: libbpf_rs::MapMut<'obj>,
        pub _blob_index_: libbpf_rs::MapMut<'obj>,
        pub _lw_task_storage_: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProbeMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut blob_ringbuf = None;
            let mut signal_ringbuf = None;
            let mut _blob_index_ = None;
            let mut _lw_task_storage_ = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "blob_ringbuf" => blob_ringbuf = Some(map),
                    "signal_ringbuf" => signal_ringbuf = Some(map),
                    "_blob_index_" => _blob_index_ = Some(map),
                    "_lw_task_storage_" => _lw_task_storage_ = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                blob_ringbuf: blob_ringbuf.expect("map `blob_ringbuf` not present"),
                signal_ringbuf: signal_ringbuf.expect("map `signal_ringbuf` not present"),
                _blob_index_: _blob_index_.expect("map `_blob_index_` not present"),
                _lw_task_storage_: _lw_task_storage_.expect("map `_lw_task_storage_` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenProbeProgs<'obj> {
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProbeProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProbeProgs<'obj> {
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProbeProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenProbeProgs<'obj>) -> Self {
            Self {
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct ProbeSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> ProbeSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenProbeSkel {
                maps: unsafe { OpenProbeMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenProbeProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for ProbeSkelBuilder {
        type Output = OpenProbeSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProbeSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 27],
            pub max_entries: *mut [i32; 1048576],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_2 {
            pub r#type: *mut [i32; 6],
            pub key: *mut u32,
            pub value: *mut u64,
            pub max_entries: *mut [i32; 1],
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_7 {
            pub creds: __anon_3,
            pub pid: __anon_4,
            pub parent: __anon_5,
            pub session_id: u32,
            pub login_uid: u32,
            pub exec: __anon_6,
            pub boot_ns: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_3 {
            pub uid: u32,
            pub gid: u32,
            pub euid: u32,
            pub egid: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_4 {
            pub pid: u32,
            pub tgid: u32,
            pub pid_ns: u32,
            pub pid_vnr: u32,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_5 {
            pub pid: u32,
            pub tgid: u32,
            pub boot_ns: u64,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_6 {
            pub filename: __anon_8,
            pub interp: __anon_8,
            pub cgroup_id: u64,
            pub args: u64,
            pub env: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_8 {
            pub str: [u8; 128],
            pub blob: __anon_9,
        }
        impl std::fmt::Debug for __anon_8 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_8 {
            fn default() -> Self {
                Self {
                    str: [u8::default(); 128],
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_9 {
            pub flag: u64,
            pub blob_id: u64,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_10 {
            pub r#type: *mut [i32; 29],
            pub map_flags: *mut [i32; 1],
            pub key: *mut u32,
            pub value: *mut __anon_7,
        }
        impl Default for __anon_10 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    map_flags: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub blob_ringbuf: __anon_1,
            pub signal_ringbuf: __anon_1,
            pub _blob_index_: __anon_2,
            pub _lw_task_storage_: __anon_10,
        }
    }
    pub struct OpenProbeSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenProbeMaps<'obj>,
        pub progs: OpenProbeProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenProbeSkel<'obj> {
        type Output = ProbeSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<ProbeSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(ProbeSkel {
                maps: unsafe { ProbeMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: ProbeProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    pub struct ProbeSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: ProbeMaps<'obj>,
        pub progs: ProbeProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    unsafe impl Send for ProbeSkel<'_> {}
    unsafe impl Sync for ProbeSkel<'_> {}

    impl<'obj> Skel<'obj> for ProbeSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
    }
    impl ProbeSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 208, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 7, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 46, 116, 101, 120, 116, 0, 46, 109, 97, 112, 115, 0, 112, 114, 111, 98, 101, 46, 98,
        112, 102, 46, 99, 0, 95, 100, 117, 109, 109, 121, 0, 98, 108, 111, 98, 95, 114, 105, 110,
        103, 98, 117, 102, 0, 115, 105, 103, 110, 97, 108, 95, 114, 105, 110, 103, 98, 117, 102, 0,
        95, 98, 108, 111, 98, 95, 105, 110, 100, 101, 120, 95, 0, 95, 108, 119, 95, 116, 97, 115,
        107, 95, 115, 116, 111, 114, 97, 103, 101, 95, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46,
        101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 29, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0,
        18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 17, 0, 4, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 17, 0, 4, 0, 16, 0, 0, 0, 0, 0,
        0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 76, 0, 0, 0, 17, 0, 4, 0, 32, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0,
        0, 0, 0, 0, 0, 89, 0, 0, 0, 17, 0, 4, 0, 64, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 152, 4,
        0, 0, 152, 4, 0, 0, 225, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 27,
        0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 2,
        0, 0, 4, 16, 0, 0, 0, 25, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 5, 0, 0, 0, 64, 0,
        0, 0, 42, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0, 0, 1, 0, 0, 0, 55, 0, 0, 0, 0, 0, 0, 14, 7, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2,
        0, 0, 0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 13, 0, 0, 0, 70, 0, 0, 0, 0, 0, 0,
        8, 14, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 8, 15, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 17, 0, 0, 0, 93, 0, 0, 0, 0, 0, 0, 8, 18, 0, 0, 0, 97,
        0, 0, 0, 0, 0, 0, 8, 19, 0, 0, 0, 103, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 122,
        0, 0, 0, 12, 0, 0, 0, 64, 0, 0, 0, 126, 0, 0, 0, 16, 0, 0, 0, 128, 0, 0, 0, 30, 0, 0, 0,
        20, 0, 0, 0, 192, 0, 0, 0, 132, 0, 0, 0, 0, 0, 0, 14, 22, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 29, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 27, 0, 0, 0, 145, 0, 0, 0, 0, 0, 0, 8, 28, 0, 0, 0, 0, 0, 0,
        0, 7, 0, 0, 4, 88, 1, 0, 0, 153, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 159, 0, 0, 0, 31, 0, 0,
        0, 128, 0, 0, 0, 163, 0, 0, 0, 33, 0, 0, 0, 0, 1, 0, 0, 170, 0, 0, 0, 13, 0, 0, 0, 128, 1,
        0, 0, 181, 0, 0, 0, 13, 0, 0, 0, 160, 1, 0, 0, 191, 0, 0, 0, 35, 0, 0, 0, 192, 1, 0, 0,
        196, 0, 0, 0, 17, 0, 0, 0, 128, 10, 0, 0, 204, 0, 0, 0, 0, 0, 0, 8, 30, 0, 0, 0, 0, 0, 0,
        0, 4, 0, 0, 4, 16, 0, 0, 0, 213, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 217, 0, 0, 0, 13, 0, 0,
        0, 32, 0, 0, 0, 221, 0, 0, 0, 13, 0, 0, 0, 64, 0, 0, 0, 226, 0, 0, 0, 13, 0, 0, 0, 96, 0,
        0, 0, 231, 0, 0, 0, 0, 0, 0, 8, 32, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 16, 0, 0, 0, 159, 0,
        0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 238, 0, 0, 0, 13, 0, 0, 0, 32, 0, 0, 0, 243, 0, 0, 0, 13, 0,
        0, 0, 64, 0, 0, 0, 250, 0, 0, 0, 13, 0, 0, 0, 96, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 8, 34, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 4, 16, 0, 0, 0, 159, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 238, 0,
        0, 0, 13, 0, 0, 0, 32, 0, 0, 0, 196, 0, 0, 0, 17, 0, 0, 0, 64, 0, 0, 0, 12, 1, 0, 0, 0, 0,
        0, 8, 36, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 4, 24, 1, 0, 0, 20, 1, 0, 0, 37, 0, 0, 0, 0, 0, 0,
        0, 29, 1, 0, 0, 37, 0, 0, 0, 0, 4, 0, 0, 36, 1, 0, 0, 17, 0, 0, 0, 0, 8, 0, 0, 46, 1, 0, 0,
        17, 0, 0, 0, 64, 8, 0, 0, 51, 1, 0, 0, 17, 0, 0, 0, 128, 8, 0, 0, 55, 1, 0, 0, 0, 0, 0, 8,
        38, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 128, 0, 0, 0, 66, 1, 0, 0, 42, 0, 0, 0, 0, 0, 0, 0,
        70, 1, 0, 0, 43, 0, 0, 0, 0, 0, 0, 0, 75, 1, 0, 0, 0, 0, 0, 8, 40, 0, 0, 0, 78, 1, 0, 0, 0,
        0, 0, 8, 41, 0, 0, 0, 83, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        3, 0, 0, 0, 0, 39, 0, 0, 0, 4, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 4, 16, 0, 0, 0,
        97, 1, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 102, 1, 0, 0, 17, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 4, 32, 0, 0, 0, 25, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 110, 1, 0, 0, 20, 0, 0, 0,
        64, 0, 0, 0, 122, 0, 0, 0, 12, 0, 0, 0, 128, 0, 0, 0, 126, 0, 0, 0, 26, 0, 0, 0, 192, 0, 0,
        0, 120, 1, 0, 0, 0, 0, 0, 14, 44, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0,
        138, 1, 0, 0, 1, 0, 0, 12, 46, 0, 0, 0, 213, 1, 0, 0, 4, 0, 0, 15, 96, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 16, 0, 0, 0, 9, 0, 0, 0, 16, 0, 0, 0, 16, 0, 0, 0, 23, 0, 0, 0, 32, 0, 0, 0,
        32, 0, 0, 0, 45, 0, 0, 0, 64, 0, 0, 0, 32, 0, 0, 0, 0, 105, 110, 116, 0, 95, 95, 65, 82,
        82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 116, 121, 112, 101, 0, 109,
        97, 120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 98, 108, 111, 98, 95, 114, 105, 110,
        103, 98, 117, 102, 0, 115, 105, 103, 110, 97, 108, 95, 114, 105, 110, 103, 98, 117, 102, 0,
        117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105,
        110, 116, 0, 117, 54, 52, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 107, 101, 121, 0, 118, 97, 108,
        117, 101, 0, 95, 98, 108, 111, 98, 95, 105, 110, 100, 101, 120, 95, 0, 108, 119, 95, 116,
        97, 115, 107, 0, 99, 114, 101, 100, 115, 0, 112, 105, 100, 0, 112, 97, 114, 101, 110, 116,
        0, 115, 101, 115, 115, 105, 111, 110, 95, 105, 100, 0, 108, 111, 103, 105, 110, 95, 117,
        105, 100, 0, 101, 120, 101, 99, 0, 98, 111, 111, 116, 95, 110, 115, 0, 108, 119, 95, 99,
        114, 101, 100, 115, 0, 117, 105, 100, 0, 103, 105, 100, 0, 101, 117, 105, 100, 0, 101, 103,
        105, 100, 0, 108, 119, 95, 112, 105, 100, 0, 116, 103, 105, 100, 0, 112, 105, 100, 95, 110,
        115, 0, 112, 105, 100, 95, 118, 110, 114, 0, 108, 119, 95, 112, 97, 114, 101, 110, 116, 0,
        108, 119, 95, 101, 120, 101, 99, 0, 102, 105, 108, 101, 110, 97, 109, 101, 0, 105, 110,
        116, 101, 114, 112, 0, 99, 103, 114, 111, 117, 112, 95, 105, 100, 0, 97, 114, 103, 115, 0,
        101, 110, 118, 0, 108, 119, 95, 98, 108, 111, 98, 115, 116, 114, 0, 115, 116, 114, 0, 98,
        108, 111, 98, 0, 117, 56, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105, 103, 110, 101, 100,
        32, 99, 104, 97, 114, 0, 102, 108, 97, 103, 0, 98, 108, 111, 98, 95, 105, 100, 0, 109, 97,
        112, 95, 102, 108, 97, 103, 115, 0, 95, 108, 119, 95, 116, 97, 115, 107, 95, 115, 116, 111,
        114, 97, 103, 101, 95, 0, 95, 100, 117, 109, 109, 121, 0, 47, 114, 111, 111, 116, 47, 68,
        101, 118, 101, 108, 111, 112, 109, 101, 110, 116, 47, 114, 117, 115, 116, 95, 98, 112, 102,
        47, 114, 117, 115, 116, 47, 108, 105, 98, 47, 46, 46, 47, 46, 46, 47, 99, 47, 115, 114, 99,
        47, 100, 117, 109, 109, 121, 47, 112, 114, 111, 98, 101, 46, 98, 112, 102, 46, 99, 0, 125,
        0, 46, 109, 97, 112, 115, 0, 46, 116, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 159, 235, 1,
        0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 28, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 219, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 47, 0, 0, 0, 16, 0, 0, 0, 219, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 145, 1, 0, 0, 211, 1, 0, 0, 1, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3,
        0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 121, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0,
        0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0,
        0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        128, 1, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 136, 1, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 107, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 232, 1, 0, 0, 0, 0, 0, 0, 145, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 8, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
